Done pigdice
05house/pigdice pull request #7
Opened 2021-12-04 07:51 UTC by soohyun21

resolve #6

2021-12-04 08:08 UTC, soohyun21 commented
아직 반복문이 익숙하지 않아서 버튼으로 동작하게 만들다보니 js가 아닌 html 파일로 만들게 되었습니다.
혹시 문제있으면 말씀해주세요!!

2021-12-06 10:16 UTC, 05house requested changes

2021-12-06 10:16 UTC, 05house commented on pigdice-practice.html
> +
1이 나오면 다음 플레이어로 넘어가는 기능 추가

2021-12-06 10:44 UTC, 05house requested changes

2021-12-06 10:44 UTC, 05house commented on pigdice-practice.html
> +    <button>play</button>
버튼 추가

2021-12-06 10:44 UTC, 05house commented on pigdice-practice.html
> +
1 나오면 다음 플레이어에게 순서 넘어가도록 수정

2021-12-12 10:27 UTC, closed without merging